language: python
python:
  - 2.7
before_install:
  - sudo apt-get update
  - sudo apt-get -y install python-pip
  - sudo pip install --upgrade pip
  - pip install --upgrade pip
  - pip install pep8
  - pip install autopep8
script:
  - num_errors_before=`find . -name \*.py -exec pep8 --ignore=E501 {} + | wc -l`
  - echo $num_errors_before
  - python setup.py install
