language: python
python:
  - 2.7
before_install:
  - sudo apt-get update
  - sudo apt-get -y install python-pip
  - sudo pip install --upgrade pip
  - pip install --upgrade pip
  - pip install pep8
  - pip install autopep8
script:
  - num_errors_before=`find . -name \*.py -exec pep8 --ignore=E501 {} + | wc -l`
  - echo $num_errors_before
  - cd "$TRAVIS_BUILD_DIR"
  - git config --global user.email "Hawkgirlgit@gmail.com"
  - git config --global user.name "Hawkgirl"
  - git checkout $TRAVIS_BRANCH

  - find . -name \*.py -exec autopep8 --ignore=E501 --recursive --aggressive --aggressive --in-place {} +
  - num_errors_after=`find . -name \*.py -exec pep8 --ignore=E501 {} + | wc -l`
  - echo $num_errors_after

  - |
        if (( $num_errors_after < $num_errors_before )); then
            git remote add origin https://Hawkgirl:${GITHUB_API_KEY}@github.com/Hawkgirl/ext_cloud.git
            git commit -a -m "PEP-8 Fix"
            git push origin master --quiet
        fi

  - cd "$TRAVIS_BUILD_DIR"
  - find . -name \*.py -exec pep8 --ignore=E501 {} +

  - python setup.py install
